Repository ComposeGears/Valkyrie, pull requests merged in 2024-08, with the labels that each got.

#120 Update README.md
  README.md
  assets/iconpack_mode_1.png
  assets/iconpack_mode_2.png
  assets/iconpack_mode_existing_1.png
  assets/iconpack_mode_existing_2.png
  assets/iconpack_mode_new_1.png
  assets/iconpack_mode_new_2.png
Labels: housekeeping

#123 Fix back handling in IconPackCreationScreen
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/creation/IconPackCreationScreen.kt
Labels: bug-fix

#122 Tidy up release sections
  .github/release.yml
  .github/workflows/release.yml
  gradle.properties
Labels: housekeeping

#125 Delete last snapshot before non-snapshot releasing
  .github/workflows/release.yml
Labels: housekeeping

#127 Refine fields and doc
  README.md
  components/generator/imagevector/src/main/kotlin/io/github/composegears/valkyrie/generator/imagevector/ImageVectorFileSpec.kt
  components/generator/imagevector/src/main/kotlin/io/github/composegears/valkyrie/generator/imagevector/ImageVectorGenerator.kt
  components/generator/imagevector/src/main/kotlin/io/github/composegears/valkyrie/generator/imagevector/spec/LazyPropertySpec.kt
  components/generator/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/imagevector/common/OutputFormatResource.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/ui/OutputFormatSection.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/MainActivity.kt
Labels: housekeeping

#129 Verify plugin on 2024.2.0.1
  .github/workflows/release.yml
Labels: housekeeping

#137 Add support for K2 mode
  idea-plugin/src/main/resources/META-INF/plugin.xml
Labels: bug-fix

#138 Verify on IntelliJ "2024.2.0.2"
  .github/workflows/release.yml
Labels: housekeeping

#139 Mark indent_size 4 for XML
  .editorconfig
  idea-plugin/src/main/resources/META-INF/plugin.xml
Labels: housekeeping

#141 UI adjustments, allow to navigate to IntroScreen from Conversion
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/ValkyriePlugin.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/intro/IntroScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/IconPackConversionScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/IconPackPickerStateUi.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/foundation/ChoosePackDirectory.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/simple/conversion/SimpleConversionScreen.kt
Labels: feature

#142 Add info about K2 mode
  README.md
Labels: housekeeping

#136 Create ImageVectorPreviewEditorProvider to preview ImageVector inside kt file
  components/extensions/build.gradle.kts
  components/extensions/src/main/kotlin/io/github/composegears/valkyrie/extensions/Any.kt
  components/extensions/src/main/kotlin/io/github/composegears/valkyrie/extensions/Color.kt
  components/extensions/src/test/kotlin/io/github/composegears/valkyrie/extensions/ColorTest.kt
  components/ir/build.gradle.kts
  components/ir/src/main/kotlin/io/github/composegears/valkyrie/ir/IrImageVector.kt
  components/psi/iconpack/src/main/kotlin/io/github/composegears/valkyrie/psi/iconpack/IconPackPsiParser.kt
  components/psi/imagevector/build.gradle.kts
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/extension/PsiElement.kt
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/ImageVectorPsiParser.kt
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/FillParser.kt
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/IrToImageVector.kt
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/KtCallExpression.kt
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/PathNodeParser.kt
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/parser/MaterialImageVectorPsiParser.kt
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/parser/RegularImageVectorPsiParser.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/ImageVectorPsiParserTest.kt
  components/psi/imagevector/src/test/resources/AllPathParams.kt
  components/psi/imagevector/src/test/resources/EmptyImageVector.kt
  components/psi/imagevector/src/test/resources/EmptyPaths.kt
  components/psi/imagevector/src/test/resources/IconWithGradient.kt
  components/psi/imagevector/src/test/resources/IconWithGroup.kt
  components/psi/imagevector/src/test/resources/LazyProperty.kt
  components/psi/imagevector/src/test/resources/MaterialIcon.kt
  idea-plugin/build.gradle.kts
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/ImageVectorPreviewEditorProvider.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/TextEditorWithImageVectorPreview.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/existingpack/ui/viewmodel/ExistingPackViewModel.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/viewmodel/NewPackViewModel.kt
  idea-plugin/src/main/resources/META-INF/plugin.xml
  settings.gradle.kts
Labels: feature

#152 Revert "Update plugin android-application to v8.6.0"
  gradle/libs.versions.toml
Labels: housekeeping

#151 Introduce ImageVectorPreview actions
  components/parser/ktfile/build.gradle.kts
  components/parser/ktfile/src/main/kotlin/io/github/composegears/valkyrie/parser/ktfile/util/IrToImageVector.kt
  idea-plugin/build.gradle.kts
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/TextEditorWithImageVectorPreview.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/VirtualFile.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/ui/ImageVectorPreviewPanel.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/ui/error/PreviewParsingError.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/ui/previewer/ImageVectorPreview.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/ui/previewer/TopActions.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/ui/previewer/ZoomState.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/ClickableText.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/TooltipButton.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/ActualZoom.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/BlackCircle.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Chessboard.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Error.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/FitContent.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/WhiteCircle.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/ZoomIn.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/ZoomOut.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/platform/Browser.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/previewbg/BgType.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/previewbg/PreviewBackground.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/batch/IconPreviewBox.kt
Labels: feature
