Repository ComposeGears/Valkyrie, pull requests merged in 2024-09, with the labels that each got.

#155 Handle camelCase icon names, introduce IconNameFormatter
  components/parser/svgxml/src/main/kotlin/io/github/composegears/valkyrie/parser/svgxml/IconNameFormatter.kt
  components/parser/svgxml/src/main/kotlin/io/github/composegears/valkyrie/parser/svgxml/SvgXmlParser.kt
  components/parser/svgxml/src/test/kotlin/io/github/composegears/valkyrie/parser/svgxml/IconNameFormatterTest.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/IconPackConversionViewModel.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/BatchProcessingStateUi.kt
Labels: feature

#161 Move IntelliJ compose wrappers into platform package
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/ui/error/PreviewParsingError.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/picker/Picker.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/Browser.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/DragAndDropHandler.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/IntellijEditor.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/NotificationManager.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/picker/DirectoryPicker.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/picker/FilePicker.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/picker/MultipleFilesPicker.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/picker/Picker.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/IconPackPickerStateUi.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/existingpack/ui/foundation/ChooseExistingPackFile.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/foundation/ChoosePackDirectory.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/simple/conversion/SimpleConversionScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/preview/CodePreviewScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/AboutSettingsScreen.kt
Labels: housekeeping

#168 Validate on IJ 2024.2.2
  .github/workflows/release.yml
Labels: housekeeping

#169 Unset "untilBuild" property
  idea-plugin/build.gradle.kts
Labels: housekeeping

#170 Revert gradle 8.10.1 to 8.10
  gradle/wrapper/gradle-wrapper.properties
Labels: housekeeping

#172 Update Formatter.kt
  components/generator/common/src/main/kotlin/io/github/composegears/valkyrie/generator/ext/Formatter.kt
Labels: housekeeping

#174 Show Export path and Package in settings, make path relative to the current project
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/InfoItem.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/CurrentProject.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/foundation/ChoosePackDirectory.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/GeneralSettingsScreen.kt
Labels: feature

#177 Clear backstack after navigation to conversion screens
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/IconPackConversionScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/IconPackConversionViewModel.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/existingpack/ExistingPackScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/NewPackScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/simple/setup/SimpleModeSetupScreen.kt
Labels: bug-fix

#178 Fix crash when drag-and-drop folder into Existing pack
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/existingpack/ui/foundation/ChooseExistingPackFile.kt
Labels: bug-fix

#176 Create IDEA actions to choose export folder and import files
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ValkyrieToolWindow.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/action/ExportHereAction.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/action/ImportFromDirectoryOrFileAction.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/action/dialog/RequiredIconPackModeDialog.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/ImageVectorPreviewEditorProvider.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/service/GlobalEventsHandler.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/service/PersistentSettings.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/settings/InMemorySettings.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/ValkyriePlugin.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/di/Koin.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/theme/Theme.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/IconPackConversionScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/IconPackConversionViewModel.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/creation/common/inputhandler/InputHandler.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/existingpack/ui/viewmodel/ExistingPackInputHandler.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/viewmodel/NewPackInputHandler.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/viewmodel/NewPackViewModel.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/GeneralSettingsScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/ImageVectorPreviewSettingsScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/export/ImageVectorExportSettingsScreen.kt
  idea-plugin/src/main/resources/META-INF/plugin.xml
Labels: feature

#182 Verify on "2024.2.3"
  .github/workflows/release.yml
Labels: housekeeping

#183 Make GeneralSettingsScreen scrollable, move "Danger zone" to bottom of screen
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/GeneralSettingsScreen.kt
Labels: feature

#184 UI adjustments
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/intro/IntroScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/creation/IconPackCreationScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/existingpack/ExistingPackScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/NewPackScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/foundation/NewPackCreation.kt
Labels: housekeeping
