Repository ComposeGears/Valkyrie, pull requests merged in 2025-04, with the labels that each got.

#398 Add telegram link, update badges
  README.md
Labels: housekeeping

#405 [IconPack] Preview action crash if icon pasted from clipboard
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/batch/BatchProcessingStateUi.kt
Labels: bugfix-plugin

#404 Add basic ValkyrieStrings to load strings from bundle, migrate IntroScreen
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/intro/IntroScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/util/ValkyrieStrings.kt
  idea-plugin/src/main/resources/messages/Valkyrie.properties
Labels: housekeeping

#406 Add possibility to enable/disable usage compose predefined color
  cli/src/main/kotlin/io/github/composegears/valkyrie/cli/command/SvgXmlToImageVectorCommand.kt
  components/generator/imagevector/src/main/kotlin/io/github/composegears/valkyrie/generator/imagevector/ImageVectorFileSpec.kt
  components/generator/imagevector/src/main/kotlin/io/github/composegears/valkyrie/generator/imagevector/ImageVectorGenerator.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/service/PersistentSettings.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/settings/InMemorySettings.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/SettingsViewModel.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/model/SettingsAction.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/export/ImageVectorExportSettingsScreen.kt
  idea-plugin/src/main/resources/messages/Valkyrie.properties
Labels: feature-plugin, feature-cli

#413 Disable cache for validation.yml
  .github/workflows/validation.yml
Labels: housekeeping

#399 [Export] Replace color hex with predefined Compose colors
  cli/src/test/kotlin/io/github/composegears/valkyrie/cli/SvgXmlToImageVectorCliTest.kt
  components/generator/imagevector/src/main/kotlin/io/github/composegears/valkyrie/generator/imagevector/spec/Common.kt
  components/generator/imagevector/src/main/kotlin/io/github/composegears/valkyrie/generator/imagevector/util/PathBuilder.kt
  components/ir/src/main/kotlin/io/github/composegears/valkyrie/ir/IrColor.kt
  components/ir/src/test/kotlin/io/github/composegears/valkyrie/ir/HexParserTest.kt
  components/sharedTestResources/imagevector/kt/backing/ComposeColor.kt
  components/sharedTestResources/imagevector/kt/lazy/ComposeColor.kt
  components/sharedTestResources/imagevector/xml/ic_compose_color.xml
Labels: feature

#417 Clean up playground folder
  playground/app/build.gradle.kts
  playground/app/src/main/AndroidManifest.xml
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/MainActivity.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/BackingIcons.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/colored/Videocam.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/outlined/Add.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/outlined/Appearance.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/outlined/Arrow.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/outlined/ArrowLeft.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/outlined/ArrowRight.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/outlined/Brightness.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/outlined/Car.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/backing/outlined/Changelog.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/LazyIcons.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/colored/Videocam.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/outlined/Add.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/outlined/Appearance.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/outlined/Arrow.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/outlined/ArrowLeft.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/outlined/ArrowRight.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/outlined/Brightness.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/outlined/Car.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/icons/lazy/outlined/Changelog.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/ui/theme/Color.kt
  playground/app/src/main/kotlin/io/github/composegears/valkyrie/playground/ui/theme/Theme.kt
  playground/app/src/main/res/drawable/ic_launcher_foreground.xml
  playground/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  playground/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  playground/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  playground/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  playground/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  playground/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  playground/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  playground/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  playground/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  playground/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  playground/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  playground/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  playground/app/src/main/res/values/colors.xml
  playground/app/src/main/res/values/strings.xml
  playground/app/src/main/res/values/themes.xml
Labels: housekeeping

#419 Extract separate JVM svg/xml parsers
  components/parser/jvm/svg/build.gradle.kts
  components/parser/jvm/svg/src/main/kotlin/io/github/composegears/valkyrie/parser/jvm/svg/SvgToXmlParser.kt
  components/parser/jvm/xml/build.gradle.kts
  components/parser/jvm/xml/src/main/kotlin/io/github/composegears/valkyrie/parser/jvm/xml/PathNode.kt
  components/parser/jvm/xml/src/main/kotlin/io/github/composegears/valkyrie/parser/jvm/xml/PathParser.kt
  components/parser/jvm/xml/src/main/kotlin/io/github/composegears/valkyrie/parser/jvm/xml/XmlToImageVectorParser.kt
  components/parser/jvm/xml/src/main/kotlin/io/github/composegears/valkyrie/parser/jvm/xml/ext/Ir.kt
  components/parser/jvm/xml/src/main/kotlin/io/github/composegears/valkyrie/parser/jvm/xml/ext/XmlPullParser.kt
  components/parser/svgxml/build.gradle.kts
  components/parser/svgxml/src/main/kotlin/io/github/composegears/valkyrie/parser/svgxml/SvgXmlParser.kt
  components/parser/svgxml/src/main/kotlin/io/github/composegears/valkyrie/parser/svgxml/svg/SvgToXmlParser.kt
  settings.gradle.kts
Labels: housekeeping

#420 [IR][Preview] Handle predefined Compose colors during parsing
  components/ir/src/main/kotlin/io/github/composegears/valkyrie/ir/IrColor.kt
  components/ir/src/test/kotlin/io/github/composegears/valkyrie/ir/HexParserTest.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/KtFileToImageVectorParserTest.kt
  components/psi/imagevector/build.gradle.kts
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/KtCallExpression.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/KtCallExpressionTests.kt
Labels: feature

#424 Verify on min and max supported IDEA version
  .github/workflows/release.yml
Labels: housekeeping

#423 Update cli result message
  cli/src/main/kotlin/io/github/composegears/valkyrie/cli/command/SvgXmlToImageVectorCommand.kt
Labels: feature-cli

#422 Update proguard configuration
  cli/build.gradle.kts
  cli/proguard-rules.pro
Labels: feature-cli

#428 Setup IntelliJ plugin verify
  .github/workflows/release.yml
  idea-plugin/build.gradle.kts
Labels: housekeeping

#429 Update kotlin configuration
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: housekeeping

#431 Fix plugin not dynamic due to missing id
  idea-plugin/src/main/resources/META-INF/plugin.xml
Labels: bugfix-plugin

#432 Migrate ir-compose to kmp
  components/ir-compose/build.gradle.kts
  components/ir-compose/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/compose/IrToImageVector.kt
Labels: housekeeping

#433 Introduce convention plugins
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/ComposePlugin.kt
  build-logic/convention/src/main/kotlin/KmpPlugin.kt
  build-logic/convention/src/main/kotlin/io/github/composegears/valkyrie/extension/KotlinMultiplatformExtension.kt
  build-logic/convention/src/main/kotlin/io/github/composegears/valkyrie/internal/Plugins.kt
  build-logic/convention/src/main/kotlin/io/github/composegears/valkyrie/internal/Project.kt
  build-logic/settings.gradle.kts
  build.gradle.kts
  components/ir-compose/build.gradle.kts
  components/ir/build.gradle.kts
  components/parser/ktfile/build.gradle.kts
  gradle/libs.versions.toml
  idea-plugin/build.gradle.kts
  settings.gradle.kts
Labels: housekeeping

#104 Bump target IDEA version to 2024.2
  .github/workflows/release.yml
  .github/workflows/validation.yml
  build.gradle.kts
  cli/build.gradle.kts
  components/parser/ktfile/build.gradle.kts
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/KtFileToImageVectorParserTest.kt
  components/psi/iconpack/src/test/kotlin/io/github/composegears/valkyrie/psi/iconpack/IconPackPsiParserTest.kt
  gradle/libs.versions.toml
  idea-plugin/build.gradle.kts
Labels: housekeeping
