Repository ComposeGears/Valkyrie, pull requests merged in 2025-05, with the labels that each got.

#437 Move PathParser to :components:parser:common module
  components/parser/common/build.gradle.kts
  components/parser/common/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/common/PathNode.kt
  components/parser/common/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/common/PathParser.kt
  components/parser/jvm/xml/build.gradle.kts
  components/parser/jvm/xml/src/main/kotlin/io/github/composegears/valkyrie/parser/jvm/xml/ext/Ir.kt
  settings.gradle.kts
Labels: housekeeping

#436 Integrate kover, calculate test coverage, add label
  .github/workflows/coverage.yml
  README.md
  build.gradle.kts
  cli/build.gradle.kts
  cli/src/main/kotlin/io/github/composegears/valkyrie/cli/ext/Outputs.kt
  components/generator/common/build.gradle.kts
  components/generator/common/src/main/kotlin/io/github/composegears/valkyrie/generator/ext/Spec.kt
  components/generator/iconpack/build.gradle.kts
  components/generator/imagevector/build.gradle.kts
  components/ir/build.gradle.kts
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/util/IrImageVectorColor.kt
  components/parser/ktfile/build.gradle.kts
  components/parser/svgxml/build.gradle.kts
  components/psi/iconpack/build.gradle.kts
  components/psi/imagevector/build.gradle.kts
  components/test/coverage/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: housekeeping

#438 Add tests for cli
  cli/build.gradle.kts
  cli/src/main/kotlin/io/github/composegears/valkyrie/cli/command/SvgXmlToImageVectorCommand.kt
  cli/src/test/kotlin/io/github/composegears/valkyrie/cli/command/IconPackCommandTest.kt
  cli/src/test/kotlin/io/github/composegears/valkyrie/cli/command/SvgXmlToImageVectorCommandTest.kt
  gradle/libs.versions.toml
Labels: housekeeping

#440 Parse gradient startColor/endColor
  cli/src/test/kotlin/io/github/composegears/valkyrie/cli/SvgXmlToImageVectorCliTest.kt
  components/generator/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/imagevector/XmlToImageVectorTest.kt
  components/parser/common/build.gradle.kts
  components/parser/jvm/svg/build.gradle.kts
  components/parser/jvm/xml/build.gradle.kts
  components/parser/jvm/xml/src/main/kotlin/io/github/composegears/valkyrie/parser/jvm/xml/XmlToImageVectorParser.kt
  components/sharedTestResources/imagevector/kt/backing/ComposeColor.linear.gradient.kt
  components/sharedTestResources/imagevector/kt/backing/ComposeColor.radial.gradient.kt
  components/sharedTestResources/imagevector/kt/lazy/ComposeColor.linear.gradient.kt
  components/sharedTestResources/imagevector/kt/lazy/ComposeColor.radial.gradient.kt
  components/sharedTestResources/imagevector/xml/ic_compose_color_linear_gradient.xml
  components/sharedTestResources/imagevector/xml/ic_compose_color_radial_gradient.xml
  components/test/coverage/build.gradle.kts
Labels: feature

#441 Fix ImageVector preview with linear gradient, update tests
  components/parser/ktfile/build.gradle.kts
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/KtFileToImageVectorParserTest.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/LinearGradientParserTest.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/RadialGradientParserTest.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/common/BaseKtParserTest.kt
  components/parser/ktfile/src/test/resources/backing/IconWithGradient.kt
  components/parser/ktfile/src/test/resources/lazy/IconWithGradient.kt
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/FillParser.kt
Labels: bugfix-plugin

#442 Improve test coverage
  components/generator/common/src/main/kotlin/io/github/composegears/valkyrie/generator/model/IconPack.kt
  components/generator/common/src/test/kotlin/io/github/composegears/valkyrie/generator/model/IconPackTest.kt
  components/generator/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/imagevector/ImageVectorGeneratorPropertiesTest.kt
  components/generator/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/imagevector/TrailingCommaTest.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/util/IrImageVectorColor.kt
  components/ir/src/commonTest/kotlin/io/github/composegears/valkyrie/ir/HexParserTest.kt
  components/ir/src/commonTest/kotlin/io/github/composegears/valkyrie/ir/util/IrImageVectorColorTest.kt
  components/parser/svgxml/src/test/kotlin/io/github/composegears/valkyrie/parser/svgxml/SvgXmlParserTest.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/KtCallExpressionTests.kt
  components/sharedTestResources/imagevector/kt/backing/AllGroupParams.trailing.kt
  components/sharedTestResources/imagevector/kt/lazy/AllGroupParams.trailing.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/components/previewer/ImageVectorPreviewPanel.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/batch/BatchProcessingStateUi.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/batch/ui/IconPreviewBox.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/simple/conversion/ui/preview/SimpleConversionPreviewUi.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/simple/conversion/ui/preview/action/ui/PreviewAction.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/util/Stub.kt
Labels: housekeeping

#443 Remove material-icons-core dependency, eliminate m3 dependency
  components/ir-compose/build.gradle.kts
  components/parser/ktfile/build.gradle.kts
  components/parser/ktfile/src/test/kotlin/androidx/compose/material/icons/Icons.kt
  gradle/libs.versions.toml
Labels: housekeeping

#448 Introduce UniversalPicker component
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/common/picker/PickerEvent.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/common/picker/UniversalPicker.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/IconPackConversionScreen.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/IconPackConversionViewModel.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/batch/BatchProcessingStateUi.kt
  idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/picker/IconPackPickerStateUi.kt
  idea-plugin/src/main/resources/messages/Valkyrie.properties
Labels: housekeeping

#450 Merge all PSI tests into single file, move expected code into separate files
  components/parser/ktfile/build.gradle.kts
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/KtFileToImageVectorParserTest.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/LinearGradientParserTest.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/RadialGradientParserTest.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/common/BaseKtParserTest.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/AllGroupParams.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/AllPathParams.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/ClipPathGradient.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/ComposeColor.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/EmptyImageVector.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/EmptyPaths.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/IconWithGroup.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/LinearGradient.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/MaterialIcon.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/RadialGradient.kt
  components/parser/ktfile/src/test/kotlin/io/github/composegears/valkyrie/parser/ktfile/expected/SinglePath.kt
Labels: housekeeping

#451 Merge :parser:ktfile with :psi:imagevector
  components/parser/ktfile/build.gradle.kts
  components/parser/ktfile/src/main/kotlin/io/github/composegears/valkyrie/parser/ktfile/KtFileToImageVectorParser.kt
  components/psi/imagevector/build.gradle.kts
  components/psi/imagevector/src/test/kotlin/androidx/compose/material/icons/Icons.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/KtCallExpressionTests.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/KtFileToImageVectorParserTest.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/KtFile.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/common/ParseType.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/AllGroupParams.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/AllPathParams.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/ClipPathGradient.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/ComposeColor.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/EmptyImageVector.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/EmptyPaths.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/IconWithGroup.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/LinearGradient.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/MaterialIcon.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/RadialGradient.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/expected/SinglePath.kt
  components/psi/imagevector/src/test/resources/backing/AllPathParams.kt
  components/psi/imagevector/src/test/resources/backing/EmptyImageVector.kt
  components/psi/imagevector/src/test/resources/backing/EmptyPaths.kt
  components/psi/imagevector/src/test/resources/backing/IconWithGroup.kt
  components/psi/imagevector/src/test/resources/backing/MaterialIcon.kt
  components/psi/imagevector/src/test/resources/backing/SinglePath.kt
  components/psi/imagevector/src/test/resources/lazy/AllPathParams.kt
  components/psi/imagevector/src/test/resources/lazy/EmptyImageVector.kt
  components/psi/imagevector/src/test/resources/lazy/EmptyPaths.kt
  components/psi/imagevector/src/test/resources/lazy/IconWithGroup.kt
  components/psi/imagevector/src/test/resources/lazy/SinglePath.kt
  components/test/coverage/build.gradle.kts
  idea-plugin/build.gradle.kts
  settings.gradle.kts
Labels: housekeeping

#452 Add KMP XML parser module
  components/parser/kmp/xml/build.gradle.kts
  components/parser/kmp/xml/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/xml/AndroidColorParser.kt
  components/parser/kmp/xml/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/xml/VectorDrawable.kt
  components/parser/kmp/xml/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/xml/XmlDeserializer.kt
  components/parser/kmp/xml/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/xml/XmlToImageVectorParser.kt
  components/parser/kmp/xml/src/commonTest/kotlin/io/github/composegears/valkyrie/parser/kmp/xml/AndroidColorParserTest.kt
  components/parser/kmp/xml/src/commonTest/kotlin/io/github/composegears/valkyrie/parser/kmp/xml/XmlDeserializerTest.kt
  components/parser/kmp/xml/src/commonTest/kotlin/io/github/composegears/valkyrie/parser/kmp/xml/XmlToImageVectorParserTest.kt
  components/test/coverage/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: feature

#454 Extract enums, classes and interfaces from IrImageVector.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/IrFill.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/IrImageVector.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/IrPathFillType.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/IrPathNode.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/IrStroke.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/IrStrokeLineCap.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/IrStrokeLineJoin.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/IrVectorNode.kt
Labels: housekeeping

#456 Change `IrGroup` paths to nodes
  components/generator/imagevector/src/main/kotlin/io/github/composegears/valkyrie/generator/imagevector/spec/Common.kt
  components/ir-compose/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/compose/IrToImageVector.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/IrVectorNode.kt
  components/ir/src/commonMain/kotlin/io/github/composegears/valkyrie/ir/util/IrImageVectorColor.kt
  components/ir/src/commonTest/kotlin/io/github/composegears/valkyrie/ir/util/IrImageVectorColorTest.kt
  components/parser/jvm/xml/src/main/kotlin/io/github/composegears/valkyrie/parser/jvm/xml/XmlToImageVectorParser.kt
  components/parser/kmp/xml/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/xml/XmlToImageVectorParser.kt
  components/parser/kmp/xml/src/commonTest/kotlin/io/github/composegears/valkyrie/parser/kmp/xml/XmlToImageVectorParserTest.kt
  components/psi/imagevector/src/main/kotlin/io/github/composegears/valkyrie/psi/imagevector/parser/RegularImageVectorPsiParser.kt
Labels: housekeeping

#462 Add kmp svg parser
  build.gradle.kts
  components/parser/kmp/svg/build.gradle.kts
  components/parser/kmp/svg/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/KeywordColorParser.kt
  components/parser/kmp/svg/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/SVG.kt
  components/parser/kmp/svg/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/SVGDeserializer.kt
  components/parser/kmp/svg/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/SVGParser.kt
  components/parser/kmp/svg/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/SVGStroke.kt
  components/parser/kmp/svg/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/Scale.kt
  components/parser/kmp/svg/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/SvgColorParser.kt
  components/parser/kmp/svg/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/SvgExtensions.kt
  components/parser/kmp/svg/src/commonMain/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/Translation.kt
  components/parser/kmp/svg/src/commonTest/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/KeywordColorParserTest.kt
  components/parser/kmp/svg/src/commonTest/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/SVGDeserializerTest.kt
  components/parser/kmp/svg/src/commonTest/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/SVGParserTest.kt
  components/parser/kmp/svg/src/commonTest/kotlin/io/github/composegears/valkyrie/parser/kmp/svg/Utils.kt
  settings.gradle.kts
Labels: feature

#472 Setup Gemini config
  .gemini/config.yaml 
Labels: housekeeping

#470 Remove binaries.executable() for kmp libraries
  build-logic/convention/src/main/kotlin/io/github/composegears/valkyrie/extension/KotlinMultiplatformExtension.kt
Labels: housekeeping

#471 Move cli into tools folder
  .github/workflows/release.yml
  README.md
  components/test/coverage/build.gradle.kts
  settings.gradle.kts
  tools/cli/build.gradle.kts
  tools/cli/proguard-rules.pro
  tools/cli/src/main/kotlin/io/github/composegears/valkyrie/cli/Main.kt
  tools/cli/src/main/kotlin/io/github/composegears/valkyrie/cli/command/IconPackCommand.kt
  tools/cli/src/main/kotlin/io/github/composegears/valkyrie/cli/command/SvgXmlToImageVectorCommand.kt
  tools/cli/src/main/kotlin/io/github/composegears/valkyrie/cli/ext/Option.kt
  tools/cli/src/main/kotlin/io/github/composegears/valkyrie/cli/ext/Outputs.kt
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/IconPackCliTest.kt
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/SvgXmlToImageVectorCliTest.kt
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/command/IconPackCommandTest.kt
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/command/SvgXmlToImageVectorCommandTest.kt
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/common/CliTestType.kt
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/common/CommandLineTestRunner.kt
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/common/OutputFormatResource.kt
Labels: housekeeping

#468 Migrate extensions to kmp
  components/extensions/build.gradle.kts
  components/extensions/src/commonMain/kotlin/io/github/composegears/valkyrie/extensions/Any.kt
  components/extensions/src/jvmMain/kotlin/io/github/composegears/valkyrie/extensions/PathUtils.kt
  components/extensions/src/jvmMain/kotlin/io/github/composegears/valkyrie/extensions/ResourceUtils.kt
Labels: housekeeping

#466 Setup CMP application
  README.md
  gradle/libs.versions.toml
  settings.gradle.kts
  tools/compose-app/build.gradle.kts
  tools/compose-app/src/commonMain/kotlin/io/github/composegears/valkyrie/ValkyrieApp.kt
  tools/compose-app/src/desktopMain/kotlin/io/github/composegears/valkyrie/main.kt
  tools/compose-app/src/wasmJsMain/kotlin/io/github/composegears/valkyrie/main.kt
  tools/compose-app/src/wasmJsMain/resources/images/logo_114.png
  tools/compose-app/src/wasmJsMain/resources/images/logo_256.png
  tools/compose-app/src/wasmJsMain/resources/images/logo_512.png
  tools/compose-app/src/wasmJsMain/resources/index.html
  tools/compose-app/src/wasmJsMain/resources/manifest.json
  tools/compose-app/src/wasmJsMain/resources/styles.css
Labels: housekeeping

#475 Create compose-core
  compose/core/build.gradle.kts
  compose/core/src/commonMain/kotlin/io/github/composegears/valkyrie/compose/core/RememberMutableState.kt
  settings.gradle.kts
  tools/idea-plugin/build.gradle.kts
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/editor/ui/VirtualFileImageVector.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/common/picker/UniversalPicker.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/DragAndDropBox.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/FocusableTextField.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/components/previewer/ImageVectorPreviewPanel.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/highlights/KotlinCodeViewer.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/highlights/core/CodeEditor.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/platform/DragAndDropHandler.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/batch/BatchProcessingStateUi.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/existingpack/ui/foundation/ChooseExistingPackFile.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/foundation/NewPackCreation.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/simple/conversion/ui/SimpleConversionPickerStateUI.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/simple/conversion/ui/preview/SimpleConversionPreviewUi.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/GeneralSettingsScreen.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/export/IndentSizeSection.kt
Labels: housekeeping

#476 Create compose-icons, introduce Outlined icon type
  compose/icons/build.gradle.kts
  compose/icons/src/commonMain/kotlin/io/github/composegears/valkyrie/compose/icons/ValkyrieIcons.kt
  compose/icons/src/commonMain/kotlin/io/github/composegears/valkyrie/compose/icons/outlined/Conversion.kt
  settings.gradle.kts
  tools/idea-plugin/build.gradle.kts
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/action/dialog/RequiredIconPackModeDialog.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/common/picker/UniversalPicker.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/FocusableTextField.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/InputField.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/TextWithIcon.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/TooltipButton.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/TopAppBar.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/components/previewer/PreviewParsingError.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/components/previewer/TopActions.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/highlights/CodeViewerTooltip.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/ActualZoom.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/AddFile.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Back.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Backspace.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/BatchProcessing.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/BlackCircle.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Checked.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Chessboard.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Close.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Copy.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Edit.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Error.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/ExternalLink.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/FitContent.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Folder.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Help.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/KotlinLogo.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/PlayForward.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/PluginIcon.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Settings.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/ValkyrieIcons.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Visibility.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Warning.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/Watch.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/WhiteCircle.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/ZoomIn.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/foundation/icons/ZoomOut.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/intro/IntroScreen.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/DragAndDropOverlay.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/conversion/ui/batch/BatchProcessingStateUi.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/existingpack/ui/foundation/ChooseExistingPackFile.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/existingpack/ui/foundation/ExistingPackEditor.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/foundation/ChoosePackDirectory.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/iconpack/newpack/ui/foundation/NewPackCreation.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/mode/simple/conversion/ui/SimpleConversionPickerStateUI.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/AboutSettingsScreen.kt
  tools/idea-plugin/src/main/kotlin/io/github/composegears/valkyrie/ui/screen/settings/tabs/GeneralSettingsScreen.kt
Labels: housekeeping

#484 Remove Gemini config
  .gemini/config.yaml 
Labels: housekeeping

#486 Don't validate APIs for compose-app module
  build.gradle.kts
  tools/compose-app/api/compose-app.api
  tools/compose-app/api/compose-app.klib.api
Labels: housekeeping

#492 Try out @ParameterizedClass for tests
  components/generator/jvm/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/jvm/imagevector/CustomPackageTest.kt
  components/generator/jvm/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/jvm/imagevector/ExplicitModeTest.kt
  components/generator/jvm/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/jvm/imagevector/ImageVectorWithIndentTest.kt
  components/generator/jvm/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/jvm/imagevector/ImageVectorWithPreviewTest.kt
  components/generator/jvm/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/jvm/imagevector/SvgWithGradientToImageVectorTest.kt
  components/generator/jvm/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/jvm/imagevector/TrailingCommaTest.kt
  components/generator/jvm/imagevector/src/test/kotlin/io/github/composegears/valkyrie/generator/jvm/imagevector/XmlToImageVectorTest.kt
  components/psi/imagevector/src/test/kotlin/io/github/composegears/valkyrie/psi/imagevector/KtFileToImageVectorParserTest.kt
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/IconPackCliTest.kt
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/SvgXmlToImageVectorCliTest.kt
Labels: housekeeping

#493 Remove the workaround for Junit5 issue 2811
  tools/cli/src/test/kotlin/io/github/composegears/valkyrie/cli/IconPackCliTest.kt
Labels: housekeeping
